console.log('Happy developing ✨')
console.log('Actor:', process.env.ACTOR)
console.log('Name:', process.env.NAME)
console.log('MY_NAME:', process.env.MY_NAME)
console.log('TIME_Z:', process.env.TIME_Z)
console.log('MY_SECRET:', process.env.MY_SECRET)