name: Hello World Action
on: [push]
jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Get source code
        uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22
      - run: node index.js
